import './globals.css'
import Sidebar from '../components/Sidebar'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="h-full">
            <body className="h-full overflow-hidden">
                <Sidebar />

                <main className="ml-72 h-screen overflow-auto bg-gray-50 p-6">
                    {children}
                </main>
            </body>
        </html>
    )
}